<?php

/**
 * The current theme path
 */
define('MAPIBAR_THEME_PATH', '/' . drupal_get_path('theme', variable_get('theme_default', NULL)));
define('MAPIBAR_MODULE_PATH', '/sites/all/modules/mapibar');
define('MAPIBAR_URL_PATH', 'https://');

/**
 * Ancho de la barra
 */
define('MAPIBAR_WIDTH', 1240);

/**
 * Ventana de Chat
 */
define('MAPIBAR_CHAT', MAPIBAR_THEME_PATH . '/chats/chat.php');

/**
 * WhatsApp
 */
define('MAPIBAR_WHATSAPP', '+51984630919, +51984983720');

/**
 * Emails
 */
define('MAPIBAR_MAIL', 'info@machupicchu.biz,machupicchutravel@hotmail.com');

/**
 * Responsabilidad Social
 */
define('MAPIBAR_RSOCIAL', '/agencia-de-viajes-y-turismo-con-responsabilidad-social');


/**
 * Precio Url
 */
define('MAPIBAR_PREMIO', 'machupicchu.biz/url-de-premio/');

/**
 * Social Networks: Facebook
 */
define('MAPIBAR_SOCIAL_F', 'machupicchu.biz/url-de-premio/');
/**
 * Social Networks: Twitter
 */
define('MAPIBAR_SOCIAL_T', 'machupicchu.biz/url-de-premio/');
/**
 * Social Networks: Instagram
 */
define('MAPIBAR_SOCIAL_I', 'machupicchu.biz/url-de-premio/');
/**
 * Social Networks: Youtube
 */
define('MAPIBAR_SOCIAL_Y', 'machupicchu.biz/url-de-premio/');


/**
* Permisos
* @return array An array of valid permissions for the mapibar module
*/
function mapibar_permission() {
  return array('administer mapibar' => array(
      'title' => t('Administer values for Mapibar'),
  ));
} // function mapibar_perm()

/**
* Muestra el menú y llama al Admin
* @return array
*/
function mapibar_menu() {
  $items = array();

  $items['admin/mapitravel'] = array(
    'title' => 'Machupicchu',
    'description' => 'All modules for Machupicchu Travel',
    'position' => 'right',
    'weight' => 0,
    'access arguments' => array('access administration pages'),
  );
  $items['admin/mapitravel/mapibar'] = array(
    'title' => 'MapiBar',
    'description' => 'Config values for Mapibar',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mapibar_admin'),
    'access arguments' => array('access administration pages'),
   );

  return $items;
} // function mapibar_menu()

/**
* Init
*/
function mapibar_init() {
    $path = drupal_get_path('module', 'mapibar');
    drupal_add_css($path .'/mapibar.css');
    drupal_add_js($path .'/mapibar.js');
    if ($setting = variable_get('mapibar_width', MAPIBAR_WIDTH)) {
      drupal_add_js(array('mapibar' => array('width' => $setting)), 'setting');
    }
    if ($setting = variable_get('mapibar_chat', MAPIBAR_CHAT)) {
      drupal_add_js(array('mapibar' => array('chat' => $setting)), 'setting');
    }
	  if ($setting = variable_get('mapibar_whatsapp', MAPIBAR_WHATSAPP)) {
      drupal_add_js(array('mapibar' => array('whatsapp' => $setting)), 'setting');
    }
    
} // function mapibar_init()

/**
* Página de Administración de MapiBar
* @return array El Formulario
*/
function mapibar_admin() {
  $form = array();

  $form['contact'] = array(
      '#type' => 'fieldset',
      '#title' => t('Contact'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
  );

  $form['social_net'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social Networks'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['variables'] = array(
      '#type' => 'fieldset',
      '#title' => t('Settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
  );

  $form['languages'] = array(
      '#type' => 'fieldset',
      '#title' => t('Languages'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
  );

  $form['languages']['en'] = array(
      '#type' => 'fieldset',
      '#title' => t('English'),
      '#collapsible' => FALSE,
  );

  $form['languages']['br'] = array(
      '#type' => 'fieldset',
      '#title' => t('Portuguese'),
      '#collapsible' => FALSE,
  );

  $form['languages']['es'] = array(
      '#type' => 'fieldset',
      '#title' => t('Spanish'),
      '#collapsible' => FALSE,
  );
    


  // Contacto
  $form['contact']['mapibar_whatsapp'] = array(
    '#type' => 'textfield',
    '#title' => t('WhatsApp'),
    '#default_value' => variable_get('mapibar_whatsapp', MAPIBAR_WHATSAPP),
    '#description' => t("Only two phones, separated by commas and no spaces."),
    '#required' => TRUE,
  );

  $form['contact']['mapibar_mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mails'),
    '#default_value' => variable_get('mapibar_mail', MAPIBAR_MAIL),
    '#description' => t("Only two mails, separated by commas and no spaces."),
    '#required' => TRUE,
  );

  $form['contact']['mapibar_rsocial'] = array(
    '#type' => 'textfield',
    '#title' => t('Responsabilidad Social URL'),
    '#default_value' => variable_get('mapibar_rsocial', MAPIBAR_RSOCIAL),
    '#description' => t("Only url RS, no spaces."),
    '#required' => TRUE,
  );

  $form['contact']['mapibar_premio'] = array(
    '#type' => 'textfield',
    '#title' => t('Premio URL'),
    '#default_value' => variable_get('mapibar_premio', MAPIBAR_PREMIO),
    '#description' => t("Only url Award, no spaces."),
    '#required' => TRUE,
  );

  //Social Networks
  $form['social_net']['mapibar_socials_f'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Facebook'),
    '#default_value' => variable_get('mapibar_socials_f', MAPIBAR_SOCIAL_F),
    '#description' => t("Only URL Facebook, no spaces."),
    '#required' => TRUE,
  );
  $form['social_net']['mapibar_socials_t'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Twitter'),
    '#default_value' => variable_get('mapibar_socials_t', MAPIBAR_SOCIAL_T),
    '#description' => t("Only URL Twitter, no spaces."),
    '#required' => TRUE,
  );
  $form['social_net']['mapibar_socials_i'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Instagram'),
    '#default_value' => variable_get('mapibar_socials_i', MAPIBAR_SOCIAL_I),
    '#description' => t("Only URL Instagram, no spaces."),
    '#required' => TRUE,
  );
  $form['social_net']['mapibar_socials_y'] = array(
    '#type' => 'textfield',
    '#title' => t('URL Youtube'),
    '#default_value' => variable_get('mapibar_socials_y', MAPIBAR_SOCIAL_Y),
    '#description' => t("Only URL Youtube, no spaces."),
    '#required' => TRUE,
  );

  // Variables
  $form['variables']['mapibar_chat'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for Chat window'),
    '#size' => 60,
    '#default_value' => variable_get('mapibar_chat', MAPIBAR_CHAT),
    '#maxlength' => 300,
    '#required' => TRUE,
  );

  $form['variables']['mapibar_width'] = array(
    '#type' => 'textfield',
    '#title' => t('The bar width in px'),
    '#size' => 10,
    '#default_value' => variable_get('mapibar_width', MAPIBAR_WIDTH),
    '#maxlength' => 4,
    '#required' => TRUE,
  );

// Idiomas
  $form['languages']['en']['mapibar_en_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for english site (Optional)'),
    '#default_value' => variable_get('mapibar_en_url', 'https://www.machupicchutravelagency.com'),
  );
  $form['languages']['en']['mapibar_en_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for url in english (Optional)'),
    '#default_value' => variable_get('mapibar_en_title', 'Travel to Machu Picchu'),
  );

  $form['languages']['br']['mapibar_br_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for portuguese site (Optional)'),
    '#default_value' => variable_get('mapibar_br_url', 'https://brasil.machupicchu.biz'),
  );
  $form['languages']['br']['mapibar_br_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for url in portuguese (Optional)'),
    '#default_value' => variable_get('mapibar_br_title', 'Pacotes a Machu Picchu'),
  );

  $form['languages']['es']['mapibar_es_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL for spanish site (Optional)'),
    '#default_value' => variable_get('mapibar_es_url', 'https://www.machupicchu.biz'),
  );
  $form['languages']['es']['mapibar_es_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title for url in spanish (Optional)'),
    '#default_value' => variable_get('mapibar_es_title', 'Tours a Machu Picchu'),
  );

  return system_settings_form($form);
}

// function mapibar_admin()

/**
 *
 * @param
 *  type $var lo que se va a juntar
 * @return
 *  string lo juntado
 */
function mapibar_joiner($var) {
    $var = str_replace(',', '<br />', $var);
    return $var;
}
function mapibar_joiner_socials($var) {
    $var = str_replace(',', '', $var);
    return $var;
}

/**
 * The bar
 */
function mapibar_page_build(&$page) {
	global $language;

  $output = sprintf('
    <div id="topbar" style="height: 50px;position: fixed;top: 0;">
      <div id="contact-bar">
        <ul>
        <li id="cb-chat"><div class="cb-chat"></div><div>%s</div></li>
        <li id="cb-whatsapp"><a href="https://wa.me/51984630919?text=Hola, est@y interesado en:" target="blank"><div class="wpp-bg"><div class="phone"></div></div><div>%s %s</div></a></li>
        <li class="cb-mail"><span class="span">%s</span><p class="p"><span>%s</span></p></li>
        <li class="cb-call">
          
          <a target="_blank" href="%s" rel="nofollow">
              <div class="cb-call_ico"></div>
              <span>%s</span>
          </a>
        
        </li>

        <li id="cb-socials"><span class="span">%s</span>
          <ul>
            <li>
                <a href="%s" target="_blank" rel="nofollow">
                    <i class="fab"></i>
                </a>
            </li>
            <li>
                <a href="%s" target="_blank" rel="nofollow">
                    <i class="twi"></i>
                </a>
            </li>
            <li>
                <a href="%s" target="_blank" rel="nofollow">
                    <i class="ins"></i>
                </a>
            </li>
            <li>
                <a href="%s" target="_blank" rel="nofollow">
                    <i class="you"></i>
                </a>
            </li>
          </ul>      
        </li>

        <li class="cb-award"><span class="span">%s</span><a href="%s" target="_blank"><span class="cb-award_ico"></span></a></li>
        <li id="cb-langs" class="idiomas last">',
            t('Chatea con nosotros'),
            t(''),
              mapibar_joiner(variable_get('mapibar_whatsapp', MAPIBAR_WHATSAPP)),            
            t('Book 24 hours'),
            mapibar_joiner(variable_get('mapibar_mail', MAPIBAR_MAIL)),
            mapibar_joiner(variable_get('mapibar_rsocial', MAPIBAR_RSOCIAL)),
            t('Responsabilidad Social'),
            t('Redes Sociales'),
              mapibar_joiner_socials(variable_get('mapibar_socials_f', MAPIBAR_SOCIAL_F)),
              mapibar_joiner_socials(variable_get('mapibar_socials_t', MAPIBAR_SOCIAL_T)),
              mapibar_joiner_socials(variable_get('mapibar_socials_i', MAPIBAR_SOCIAL_I)),
              mapibar_joiner_socials(variable_get('mapibar_socials_y', MAPIBAR_SOCIAL_Y)),
              t('Premio'),
              mapibar_joiner(variable_get('mapibar_premio', MAPIBAR_PREMIO)));
        switch($language->language) {
          case 'es':
            $output .= sprintf('<a href="%s" title="%s"><div class="ban_en"></div><span>%s</span></a>
            <a href="%s" title="%s"><div class="ban_br"></div><span>%s</span></a>',
                                                  variable_get('mapibar_en_url', 'https://www.machupicchutravelagency.com/'),
                                                  variable_get('mapibar_en_title'),
                                                  t('EN'),
                                                  variable_get('mapibar_br_url', 'https://brasil.machupicchu.biz/'),
                                                  variable_get('mapibar_br_title'),
                                                  t('PT'));
          break;
          case 'en':
                                          $output .= sprintf('<a href="%s" title="%s"><div class="ban_br"></div><span>%s</span></a>
            <a href="%s" title="%s"><div class="ban_es"></div><span>%s</span></a>',
                                                  variable_get('mapibar_br_url', 'https://brasil.machupicchu.biz/'),
                                                  variable_get('mapibar_br_title'),
                                                  t('PT'),
                                                  variable_get('mapibar_es_url', 'https://www.machupicchu.biz/'),
                                                  variable_get('mapibar_es_title'),
                                                  t('SP'));
          break;
          default:
                                          $output .= sprintf('<a href="%s" title="%s"><div class="ban_en"></div><span>%s</span></a>
            <a href="%s" title="%s"><div class="ban_es"></div><span>%s</span></a>',
                                                  variable_get('mapibar_en_url', 'https://www.machupicchutravelagency.com/'),
                                                  variable_get('mapibar_en_title'),
                                                  t('EN'),
                                                  variable_get('mapibar_es_url', 'https://www.machupicchu.biz/'),
                                                  variable_get('mapibar_es_title'),
                                                  t('SP'));
        }
        $output .= '</li>
        </ul>
      </div>
    </div>';

		$page['page_bottom']['mapibar'] = array(
			'#type' => 'markup',
			'#markup' => $output
		);
} // function mapibar_page_build()
